spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keepnote
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    useSSL: false
server:
  port: 8089
jwt:
  key: keepnote