spring:
  data:
    mongodb:
      username: app-root
      password: root123
      database: userDb
      port: 27017
      host: mongodock
      authentication-database: userDb
  application:
    name: user-service
server:
  port: 8080
jwt:
  key: keepnote