spring:
  data:
    mongodb:
 #     authentication-database:
      username: app-root
      password: root123
      database: userDb
      port: 27017
      host: localhost
  application:
    name: category-service
server:
  port: 8083
jwt:
  key: keepnote
