spring:
  data:
    mongodb:
      username: app-root
      password: root123
      database: userDb
      port: 27017
      host: localhost
  application:
    name: note-service
server:
  port: 8082
jwt:
  key: keepnote
